project:
  type: website
  output-dir: docs

website:
  title: "kevinhorrell.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resume.qmd
      - projects.qmd

format:
  html:
    theme: 
      - zephyr
      - brand
    css: styles.css
    toc: true

editor: visual

