project:
  type: website
  output-dir: docs

website:
  title: "Kevin Horrell"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume.qmd
      - projects.qmd

format:
  html:
    theme:
      light: pulse
      dark: superhero
    css: styles.css
    toc: true
    page-layout: full

editor: visual